import json
import zipfile
from pathlib import Path

from app.services.bambu_studio import BambuStudioService
from app.services.slicer import SliceParams


SAMPLE_GCODE_METADATA = """\
; generated by BambuStudio
;LAYER_CHANGE
;Z:0.2
G1 X10 Y10 Z0.2 F3000
;LAYER_CHANGE
;Z:0.4
G1 X20 Y20 Z0.4 F3000
; filament used [mm] = 9500.00
; filament used [cm3] = 22.50
; total filament used [g] = 28.40
; total filament cost = 0.57
; estimated printing time (normal mode) = 1h 2m 0s
"""


class TestGcodeParsing:
    def test_parse_time(self):
        result = BambuStudioService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.estimated_time_seconds == 3720

    def test_parse_filament_grams(self):
        result = BambuStudioService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.filament_used_grams == 28.4

    def test_parse_filament_meters(self):
        result = BambuStudioService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.filament_used_meters == 9.5

    def test_parse_layer_count(self):
        result = BambuStudioService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.layer_count == 2

    def test_output_filename(self):
        result = BambuStudioService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.output_filename == "output.gcode.3mf"


class TestSettingsGeneration:
    def test_write_process_settings(self, tmp_path):
        params = SliceParams(layer_height=0.1, infill_percent=80, support_material=True, print_speed=100.0)
        path = BambuStudioService._write_process_settings(str(tmp_path), params)

        settings = json.loads(Path(path).read_text())
        assert settings["layer_height"] == "0.1"
        assert settings["sparse_infill_density"] == "80%"
        assert settings["enable_support"] == "1"
        assert settings["inner_wall_speed"] == "100.0"

    def test_write_process_settings_defaults(self, tmp_path):
        params = SliceParams()
        path = BambuStudioService._write_process_settings(str(tmp_path), params)

        settings = json.loads(Path(path).read_text())
        assert settings["layer_height"] == "0.2"
        assert settings["sparse_infill_density"] == "20%"
        assert settings["enable_support"] == "0"
        assert "inner_wall_speed" not in settings

    def test_write_filament_settings(self, tmp_path):
        params = SliceParams(filament_type="PETG")
        path = BambuStudioService._write_filament_settings(str(tmp_path), params)

        settings = json.loads(Path(path).read_text())
        assert settings["filament_type"] == ["PETG"]
        assert settings["filament_density"] == ["1.27"]


class TestBuildCommand:
    def test_build_command(self):
        cmd = BambuStudioService._build_command(
            "/tmp/model.stl",
            "/tmp/output.gcode.3mf",
            "/tmp/process.json",
            "/tmp/filament.json",
        )
        assert cmd[0] == "bambu-studio"
        assert "--slice" in cmd
        assert "0" in cmd
        assert "--export-3mf" in cmd
        assert "/tmp/output.gcode.3mf" in cmd
        assert "--load-settings" in cmd
        assert "/tmp/process.json" in cmd
        assert "--load-filaments" in cmd
        assert "/tmp/filament.json" in cmd
        assert cmd[-1] == "/tmp/model.stl"


class TestRead3mf:
    def test_read_gcode_from_3mf(self, tmp_path):
        # Create a fake .gcode.3mf (zip with gcode inside)
        gcode_content = "; test gcode\nG28\n"
        archive_path = tmp_path / "output.gcode.3mf"
        with zipfile.ZipFile(archive_path, "w") as zf:
            zf.writestr("Metadata/plate_1.gcode", gcode_content)

        result = BambuStudioService._read_gcode_from_3mf(str(archive_path))
        assert "; test gcode" in result
        assert "G28" in result

    def test_read_gcode_from_3mf_empty(self, tmp_path):
        archive_path = tmp_path / "empty.3mf"
        with zipfile.ZipFile(archive_path, "w") as zf:
            zf.writestr("Metadata/model.xml", "<model/>")

        result = BambuStudioService._read_gcode_from_3mf(str(archive_path))
        assert result == ""
