from app.services.prusa_slicer import PrusaSlicerService
from app.services.slicer import SliceParams


SAMPLE_GCODE_METADATA = """\
; generated by PrusaSlicer 2.9.4
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 X10 Y10 Z0.2 F3000
;LAYER_CHANGE
;Z:0.4
G1 X20 Y20 Z0.4 F3000
;LAYER_CHANGE
;Z:0.6
G1 X30 Y30 Z0.6 F3000
; filament used [mm] = 9500.00
; filament used [cm3] = 22.50
; total filament used [g] = 28.40
; total filament cost = 0.57
; estimated printing time (normal mode) = 1h 2m 0s
; estimated first layer printing time (normal mode) = 14s
"""


class TestGcodeParsing:
    def test_parse_time(self):
        result = PrusaSlicerService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.estimated_time_seconds == 3720

    def test_parse_filament_grams(self):
        result = PrusaSlicerService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.filament_used_grams == 28.4

    def test_parse_filament_meters(self):
        result = PrusaSlicerService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.filament_used_meters == 9.5

    def test_parse_layer_count(self):
        result = PrusaSlicerService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.layer_count == 3

    def test_parse_time_minutes_only(self):
        gcode = "; estimated printing time (normal mode) = 5m 30s\n"
        result = PrusaSlicerService._parse_gcode_metadata(gcode)
        assert result.estimated_time_seconds == 330

    def test_parse_time_hours_minutes_seconds(self):
        gcode = "; estimated printing time (normal mode) = 2h 15m 45s\n"
        result = PrusaSlicerService._parse_gcode_metadata(gcode)
        assert result.estimated_time_seconds == 8145


class TestBuildCommand:
    def test_build_command_defaults(self):
        cmd = PrusaSlicerService._build_command(
            "/tmp/model.stl", "/tmp/output.gcode", SliceParams()
        )
        assert cmd[0] == "prusa-slicer"
        assert "--export-gcode" in cmd
        assert "--output" in cmd
        assert "/tmp/output.gcode" in cmd
        assert "--layer-height" in cmd
        assert "0.2" in cmd
        assert "--fill-density" in cmd
        assert "20%" in cmd
        assert "--nozzle-diameter" in cmd
        assert "0.4" in cmd
        assert "--support-material" not in cmd
        assert "--perimeter-speed" not in cmd
        assert cmd[-1] == "/tmp/model.stl"

    def test_build_command_with_supports_and_speed(self):
        params = SliceParams(
            layer_height=0.1,
            infill_percent=80,
            support_material=True,
            print_speed=100.0,
            nozzle_size=0.6,
        )
        cmd = PrusaSlicerService._build_command(
            "/tmp/model.stl", "/tmp/output.gcode", params
        )
        assert "--support-material" in cmd
        assert "--perimeter-speed" in cmd
        assert "100.0" in cmd
        assert "0.1" in cmd
        assert "80%" in cmd
        assert "0.6" in cmd
