from app.services.orca_slicer import OrcaSlicerService


SAMPLE_GCODE_METADATA = """\
; generated by OrcaSlicer
; estimated printing time (normal mode) = 1h 2m 0s
; filament used [mm] = 9500.00
; filament used [g] = 28.40
; filament used [cm3] = 22.50
; filament cost = 0.57
; total layers count = 150
G28 ; home all axes
G1 X0 Y0 Z0.2 F3000
"""


class TestGcodeParsing:
    def test_parse_time(self):
        result = OrcaSlicerService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.estimated_time_seconds == 3720

    def test_parse_filament_grams(self):
        result = OrcaSlicerService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.filament_used_grams == 28.4

    def test_parse_filament_meters(self):
        result = OrcaSlicerService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.filament_used_meters == 9.5

    def test_parse_layer_count(self):
        result = OrcaSlicerService._parse_gcode_metadata(SAMPLE_GCODE_METADATA)
        assert result.layer_count == 150

    def test_parse_time_minutes_only(self):
        gcode = "; estimated printing time (normal mode) = 5m 30s\n"
        result = OrcaSlicerService._parse_gcode_metadata(gcode)
        assert result.estimated_time_seconds == 330

    def test_parse_time_hours_minutes_seconds(self):
        gcode = "; estimated printing time (normal mode) = 2h 15m 45s\n"
        result = OrcaSlicerService._parse_gcode_metadata(gcode)
        assert result.estimated_time_seconds == 8145
